### ISSUE TITLE
use `skipAnnotations = true` for PMD `AvoidDuplicateLiterals`

### ISSUE THREAD

**Issue by xupyprmv** [teamed/qulice#785] opened 2016-06-18 13:13 UTC
You can find duplicate string literals in annotations here:

https://github.com/yegor256/takes/blob/b9600a270b4efa0c873d7ced9a6304b081752d91/src/main/java/org/takes/tk/TkCORS.java#L54

I think that we have to use flag `skipAnnotations = true` for PMD `AvoidDuplicateLiterals`, to avoid warnings with string literals in annotations.

**Comment by krzyk** [comment] 2016-06-18 13:43
@xupyprmv duplicate of #760

**Closed** 2016-06-18 14:38 UTC
