### ISSUE TITLE
Static constants are not checked to have class specified.

### ISSUE THREAD

**Issue by piddubnyi** [teamed/qulice#611] opened 2016-01-12 17:11 UTC
It's a good practice to always specify a class when using static constants.
But with current version the following code is still valid.
```java
public class Foo {
    static final String FOO = "foo";

    void bar() {
        String bar = FOO;
    }
}
```
Is there a way to enable check for static constants? I think one should be added so the valid code will be:
```java
public class Foo {
    static final String FOO = "foo";

    void bar() {
        String bar = Foo.FOO;
    }
}
```

**Comment by krzyk** [comment] 2016-01-12 19:24
@davvd valid bug

**Comment by davvd** [comment] 2016-01-13 07:58
> @davvd valid bug

@krzyk I tagged this as "bug"

**Comment by davvd** [comment] 2016-01-13 09:47
@piddubnyi many thanks for the report, I topped your account for 15 mins, transaction 74514421

**Comment by krzyk** [comment] 2016-01-13 09:51
@HDouss do you want to work on it?

**Comment by HDouss** [comment] 2016-01-13 14:44
@krzyk Yes please.

**Comment by HDouss** [comment] 2016-01-13 14:51
@piddubnyi I suggest to generalize it to any static field, even if it is not a constant (final). What do you think ?

**Comment by krzyk** [comment] 2016-01-13 15:03
@davvd assign @HDouss please

**Comment by piddubnyi** [comment] 2016-01-13 15:26
@HDouss makes sense.

**Comment by davvd** [comment] 2016-01-14 07:34
> @davvd assign @HDouss please

@krzyk done. @hdouss you are assigned to this task. please proceed...

**Comment by krzyk** [comment] 2016-01-14 12:48
@yegor256 I think there is a bug in the assignment for people that have uppercase letters in their nicks, here I assigned @HDouss, he was assigned, but it is not reflected in the Assignee field in github

**Comment by HDouss** [comment] 2016-01-14 12:49
@krzyk 
>@yegor256 I think there is a bug in the assignment for people that have uppercase letters in their nicks, here I assigned @HDouss, he was assigned, but it is not reflected in the Assignee field in github

seems there are quite few bugs in github these days. Remember superfluous file changes in some PRs ?

**Comment by yegor256** [comment] 2016-01-15 00:40
@krzyk but @HDouss is not in the team "qulice", probably that's what the problem is

**Comment by yegor256** [comment] 2016-01-15 00:40
@HDouss did you join this team: https://github.com/orgs/teamed/teams/qulice

**Comment by HDouss** [comment] 2016-01-15 08:51
@yegor256 I am sure I was member of this team. Now, I am not member of it.

**Comment by HDouss** [comment] 2016-01-15 19:06
@krzyk I am again a member of qulice team.

**Comment by krzyk** [comment] 2016-01-15 20:24
@davvd assign @HDouss

**Comment by HDouss** [comment] 2016-01-15 20:39
@krzyk I was removed again from qulice team :(

**Comment by krzyk** [comment] 2016-01-15 21:10
@HDouss strange

**Comment by davvd** [comment] 2016-01-18 08:55
> @davvd assign @HDouss 

@krzyk yes, @hdouss is already assigned to this task, please go ahead!

**Comment by HDouss** [comment] 2016-01-18 16:29
@piddubnyi PR #617 reviewed and merged. Please close the issue.

**Closed** 2016-01-18 16:34 UTC
Labels: 30 mins, bug, DEV

**Comment by HDouss** [comment] 2016-01-20 08:45
@davvd Issue closed.

**Comment by davvd** [comment] 2016-01-20 09:23
@hdouss Thank you, I have added **1 hour** to your account in payment/transaction "`75129285`", time consumed: 23 hours and 38 mins; m=1418, that's why a bonus here for fast delivery; +60 to your rating, your total score is [+1232](http://www.netbout.com/b/36032?open=rating)
