### ISSUE TITLE
False positive in BED_BOGUS_EXCEPTION_DECLARATION with jcabi-aspects

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#706] opened 2016-02-13 09:34 UTC
The following code:
```java
public final class Test implements Socket {
    ...
    @Override
    @RetryOnFailure
    public void connect() throws IOException {
        this.socket.connect();
    }
    ...
}
```
Causes `[INFO] >> M C BED: Non derivable method `connect()` declares throwing an exception that isn't thrown`. 
However, both interface and `this.socket.connect()` declare `throws IOException', so I consider this as false positive.

Root cause here is annotation from jcabi-aspects on a method that throws correct exception. In that case fb-contrib can't findout that the exception is thrown. AspectJ must be doing some bytecode magic that makes it hard to detect.

Proposed solution is in https://github.com/teamed/qulice/issues/706#issuecomment-184611854

<hr id='w'>

**Comment by krzyk** [comment] 2016-02-13 09:36
@mkordas could you post complete reproducer?

**Comment by krzyk** [comment] 2016-02-13 20:38
@mkordas ping

**Comment by mkordas** [comment] 2016-02-14 00:41
@krzyk I'll try to work on isolated reproducer tomorrow

**Comment by mkordas** [comment] 2016-02-14 13:52
@krzyk cannot find isolated reproducer, closing for now

**Comment by krzyk** [comment] 2016-02-16 09:42
@mkordas I think I found when the problem exists. If we have any annotation from jcabi-aspects on a method that throws correct exception, fb-contrib can't findout that the exception is thrown.
AspectJ must be doing some bytecode magic that makes it hard to detect.
I'm wondering how to prevent it (and how to report bug to fb-contrib).
Maybe do another compilation with aspectj disabled.

**Comment by mkordas** [comment] 2016-02-16 09:56
@krzyk right, I was trying to reproduce in isolation without these annotations and I couldn't, so now it makes sense. Should I reopen the issue? I think that we should find workaround ASAP or check should be disabled, as it will cause too much noise for some projects (e.g retryable methods usually throw exceptions...)

**Comment by krzyk** [comment] 2016-02-16 10:21
@mkordas yes, let's reopen it, we need to find a way to workaround it somehow.
By tuning the jcabi-maven-plugin to store the original classes in some directory and run findbugs on them.
I was thinking that we should:
1. check that output directory has a class named `unwoven`, if it does then run FindBugs on it, if it doesn't exist then run it on the output directory.
2. document that behavior and document how to configure a project that uses jcabi-maven-plugin to support that
3. create a invoker test that uses the 2

**Comment by mkordas** [comment] 2016-02-16 18:28
@krzyk issue reopened, description updated

**Comment by krzyk** [comment] 2016-02-16 21:00
@davvd valid bug

**Comment by krzyk** [comment] 2016-02-16 21:00
@davvd this is urgent

**Comment by yegor256** [comment] 2016-02-19 04:08
@krzyk +1

**Comment by krzyk** [comment] 2016-02-19 06:40
@yegor256 it would be easier to fix it with jcabi/jcabi-maven-plugin#45

**Comment by davvd** [comment] 2016-02-24 07:21
> @davvd valid bug

@krzyk tagged this issue with "bug"

**Comment by krzyk** [comment] 2016-02-25 14:50
@davvd this is urgent

**Comment by davvd** [comment] 2016-03-01 10:08
> @davvd this is urgent

@krzyk thanks, I added "urgent" label

**Comment by davvd** [comment] 2016-03-01 10:08
> @davvd this is urgent

@krzyk "urgent" label already here

**Comment by davvd** [comment] 2016-03-01 14:05
@gumbelmj could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here. The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by gumbelmj** [comment] 2016-03-04 00:15
@davvd  please assign to someone else.

**Comment by davvd** [comment] 2016-03-04 08:39
> @davvd  please assign to someone else.

@gumbelmj -30 points to your rating :(

**Comment by davvd** [comment] 2016-03-04 08:40
> @davvd  please assign to someone else.

@gumbelmj I will assign somebody else to this issue

**Comment by krzyk** [comment] 2016-03-05 06:49
@davvd this is not urgent

**Comment by krzyk** [comment] 2016-03-05 06:49
@davvd assign me

**Comment by davvd** [comment] 2016-03-07 13:50
> @davvd this is not urgent

@krzyk OK, I un-labeled it as "urgent" tag

**Comment by davvd** [comment] 2016-03-07 13:50
> @davvd assign me

@krzyk done, the task is yours, go ahead

**Comment by davvd** [comment] 2016-03-11 11:24
@mkordas thank you for reporting this, I added 15 mins to your acc, transaction `56e2aacd3602920126000179`

**Comment by krzyk** [comment] 2016-03-15 21:53
@davvd please see PR #754

**Comment by davvd** [comment] 2016-03-16 07:23
> @davvd please see PR #754 

@krzyk will take a look at it, thanks

**Comment by davvd** [comment] 2016-03-23 08:10
@krzyk this task is in your hands for 15 days already... -30 added to your rating, at the moment it is: [+6087](http://www.netbout.com/b/35035?open=rating)

**Comment by krzyk** [comment] 2016-03-23 08:17
@davvd this is postponed

**Comment by davvd** [comment] 2016-03-23 12:44
> @davvd this is postponed

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment] 2016-03-23 12:44
> @davvd this is postponed

@krzyk no problem, I will try to find somebody else

**Comment by krzyk** [comment] 2016-04-02 06:56
@davvd this is not postponed

**Comment by krzyk** [comment] 2016-04-02 06:56
@davvd assign me

**Comment by davvd** [comment] 2016-04-04 12:15
> @davvd this is not postponed

@krzyk thanks, I removed the "postponed" tag

**Comment by davvd** [comment] 2016-04-04 12:15
> @davvd assign me

@krzyk the task is yours, please proceed

**Comment by longtimeago** [comment] 2016-04-06 18:30
@krzyk any progress so far?

**Comment by krzyk** [comment] 2016-04-06 18:43
@longtimeago nope, still waiting for a reviewer

**Comment by longtimeago** [comment] 2016-04-06 18:45
@krzyk can't you assign somebody?

**Comment by krzyk** [comment] 2016-04-06 19:02
@longtimeago well I can try, but don't keep up the hopes, as there is a dynamic limit on assigned tasks in the project (last time it was 3 max, and the count is very strange so I can't predict it)

**Comment by longtimeago** [comment] 2016-04-06 19:03
@krzyk got it, thanks!

**Comment by krzyk** [comment] 2016-04-07 13:03
@davvd this is postponed

**Comment by davvd** [comment] 2016-04-11 09:22
> @davvd this is postponed 

@krzyk right, I added "postponed" label

**Comment by davvd** [comment] 2016-04-11 09:22
> @davvd this is postponed 

@krzyk OK, I will try to assign someone else

**Comment by longtimeago** [comment] 2016-05-08 11:46
@krzyk any chance to proceed here?

**Comment by krzyk** [comment] 2016-05-08 11:56
@longtimeago I'm waiting for budget, (canary is here https://github.com/teamed/qulice/pull/753, if that one will get a reviewer it means that I can unpostponed this issue)

**Comment by longtimeago** [comment] 2016-05-08 12:06
@krzyk sad ...

**Comment by krzyk** [comment] 2016-05-30 19:51
@davvd this is urgent

**Comment by davvd** [comment] 2016-05-31 09:16
> @davvd this is urgent

@krzyk OK, I put "urgent" label here

**Comment by davvd** [comment] 2016-05-31 09:16
> @davvd this is urgent

@krzyk OK, I un-labeled it as "postponed" tags

**Comment by davvd** [comment] 2016-06-08 09:04
@dskalenko please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dskalenko** [comment] 2016-06-14 16:41
@krzyk or @mkordas 

I have implemented test to be able to fix the problem, now I am stuck , because I can't find elegant solution how I can get unwovenClassesDir parameter from jcabi-maven-plugin, I found something like this http://stackoverflow.com/questions/125389/best-way-to-access-the-runtime-configuration-of-a-maven-plugin-from-a-custom-mojo/130872#130872 
Could you please give me advice how I can do it easily?

**Comment by krzyk** [comment] 2016-06-14 16:50
@dskalenko I think we would need to wait for https://github.com/jcabi/jcabi-maven-plugin/issues/48 to be fixed other option is to temporary disable BED_BOGUS_EXCEPTION_DECLARATION check and create a puzzle to implement it after https://github.com/jcabi/jcabi-maven-plugin/issues/48 is done. Other options I think are too costly.

**Comment by dskalenko** [comment] 2016-06-15 10:10
@krzyk 
here my PR #781, please read description of PR before doing code review and let me know if I am done correctly for the moment, thanks

**Comment by davvd** [comment] 2016-06-23 10:36
@dskalenko check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck; -30 added to your rating, current score is: [+0](http://www.netbout.com/b/36376?open=rating)

**Comment by krzyk** [comment] 2016-06-25 05:44
@dskalenko now you have to ask mkordas to close the issue (if it fixes his problrm)

**Comment by krzyk** [comment] 2016-06-26 14:01
@dskalenko ping

**Comment by dskalenko** [comment] 2016-06-27 06:36
@mkordas Could you please check this issue and close if all good

**Comment by davvd** [comment] 2016-06-27 09:05
@mkordas once `706-72bdab5d`/#787 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Closed** 2016-06-27 12:44 UTC
Labels: 30 mins, bug, DEV, urgent

**Comment by krzyk** [comment] 2016-06-28 05:28
@davvd this is not urgent

**Comment by davvd** [comment] 2016-06-28 11:07
> @davvd this is not urgent

@krzyk right, I removed "urgent" tag

**Comment by davvd** [comment] 2016-06-29 11:50
@dskalenko Thanks so much! Your account was topped up for **30 mins** (transaction ID is `91616835`, the task took 482 hours and 3 mins)

added +30 to your rating, now it is equal to [+30](http://www.netbout.com/b/36376?open=rating)
