### ISSUE TITLE
Travis CI Builds are failing

### ISSUE THREAD

**Issue by aliceice** [teamed/qulice#869] opened 2018-02-12 17:53 UTC
Travis CI Builds are currently failing with:

```
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
```

See https://travis-ci.org/teamed/qulice/jobs/325029137 for example.

**Comment by 0crat** [comment] 2018-02-12 17:53
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by krzyk** [comment] 2018-04-27 10:37
@0crat in

**Comment by 0crat** [comment] 2018-04-27 10:37
> @0crat in ([here](https://github.com/teamed/qulice/issues/869#issuecomment-384933405))

@krzyk Job [#869](https://github.com/teamed/qulice/issues/869) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-04-27 10:37
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @aliceice[/z](https://www.0crat.com/u/aliceice)

**Comment by 0crat** [comment] 2018-04-27 11:36
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by krzyk** [comment] 2018-04-27 11:47
@aliceice Please merge the issue for AppVeyor into this one also

**Comment by krzyk** [comment] 2018-04-27 11:49
@0crat assign @krzyk

**Comment by 0crat** [comment] 2018-04-27 11:49
> @0crat assign @krzyk ([here](https://github.com/teamed/qulice/issues/869#issuecomment-384947496))

@krzyk The job [#869](https://github.com/teamed/qulice/issues/869) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3T49A35L/1171167287); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment] 2018-04-27 11:50
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment] 2018-04-28 09:35
@0crat out

**Comment by 0crat** [comment] 2018-04-28 09:36
> @0crat out ([here](https://github.com/teamed/qulice/issues/869#issuecomment-385158724))

@krzyk GitHub issue is still open, won't close

**Comment by krzyk** [comment] 2018-04-28 20:52
@yegor256 Could you close this one (and also $870 as a duplicate of this one)? @aliceice is out for the last 2 months and she didn't reply in any other github issues.

**Comment by krzyk** [comment] 2018-05-02 06:36
@0crat refuse

**Comment by 0crat** [comment] 2018-05-02 06:37
> @0crat refuse ([here](https://github.com/teamed/qulice/issues/869#issuecomment-385878605))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#869](https://github.com/teamed/qulice/issues/869), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment] 2018-05-02 06:37
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment] 2018-05-02 18:46
@0crat out

**Comment by 0crat** [comment] 2018-05-02 18:47
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ab56d234-9c5a-4a94-9bc9-5e54c14be93d, thread: BkParallel-6
com.mongodb.MongoCollectionImpl[558] com.mongodb.MongoWriteException: quota exceeded
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Closed** 2018-05-06 05:13 UTC
Labels: scope

**Comment by 0crat** [comment] 2018-05-06 05:30
The job is not in WBS, won't close the order
