### ISSUE TITLE
Build mysteriously fails citing a `NullPointerException` on line 0 of the class

### ISSUE THREAD

**Issue by prahladyeri** [teamed/qulice#608] opened 2016-01-12 07:35 UTC
All I changed in the header section of TkStart.java was adding a few imports (PR [921](https://github.com/yegor256/netbout/pull/921) - `netbout` project). The build, however, fails as qulice raises a `NullPointerException` on line 0 of the class :

    [ERROR] /src/main/java/com/netbout/rest/TkStart.java[0]: Got an exception - java.lang.NullPointerException (TreeWalker)

**Comment by krzyk** [comment] 2016-01-12 07:48
@prahladyeri could you run maven build with `-X` and add the checkstyle log here?
Also, do you know which change causes this NPE? You have quite a few lines changes in that file, it would be best to have minimal class file that I could use to reproduce it.

**Comment by prahladyeri** [comment] 2016-01-12 08:20
@krzyk Surprisingly, when I remove this following import statement, qulice starts working normally:

`import java.util.concurrent.ConcurrentHashMap;`

It does catch other exceptions after that, but the `NullPointerException` vanishes. Even if there is some problem with this import statement, `qulice` should highlight that instead of throwing a `NullPointerException`. So, this is not expected behavior.

PFB the DEBUG output (for the case where `NullPointerException` does occur). You will find it on line `7500`.

[nb.log.zip](https://github.com/teamed/qulice/files/86939/nb.log.zip)

**Comment by krzyk** [comment] 2016-01-12 09:14
@prahladyeri please try if it fails with latest `0.15.1` also

**Comment by prahladyeri** [comment] 2016-01-12 10:15
@krzyk The point is that the build fails on both build servers (`travis` and `appveyor`) where my PR is being built (see the PR link). Don't they use the latest qulice versions?

What will I achieve even if the latest version doesn't fail on my own personal computer? I won't be able to submit the PR until this fix is deployed on both the servers.

**Comment by krzyk** [comment] 2016-01-12 10:22
@prahladyeri qulice is configured in project not on travis or appveyor. Netbout is using right now older qulice, newer releases might have this problem solved. We can't fix problem in older release, releases numbers always increment. 

Your option is to try to configure e.g. 0.13 in netbout, maybe it will work.

**Comment by prahladyeri** [comment] 2016-01-13 05:54
@krzyk Neither the `0.13`, nor `0.15.1` fixes this. In fact, they cry for additional exceptions in various other classes. Here are links both failed builds:

[0.13](https://ci.appveyor.com/project/yegor256/netbout/build/81)

[0.15.1](https://ci.appveyor.com/project/yegor256/netbout/build/80)

**Comment by krzyk** [comment] 2016-01-13 08:02
@prahladyeri checkstyle which causes this was upgraded in 0.14 and 0.14.2, you could try those.  Unfortunately you would need to fix the style issues after that or exclude them and create todo to remove those exclusions.

**Comment by prahladyeri** [comment] 2016-01-15 09:54
@krzyk Thanks. For the time being, I've excluded `TkStart.java` and added the following todo puzzle to it:

     * @todo #750:30min Solve the puzzle for build mysteriously failing for
     *  this task citing a NullPointerException (See qulice issue #608 raised for
     *  the same) and then remove TkStart.java from qulice exceptions.

**Comment by krzyk** [comment] 2016-01-15 10:57
@prahladyeri In 0.15.1 it doesn't fail, so this ticket is invalid, there is no need to fix anything in qulice because NPE is not thrown (at least for this case), you just need to write that project has to be upgraded to newest qulice version (or at least 0.15.1, maybe some lower will also work, like 0.14 or 0.14.2).

**Comment by prahladyeri** [comment] 2016-01-15 13:33
@krzyk But 0.15.1 is not readily implementable. Either you have to exclude the class, or fix a plethora of other classes for the additional violations thrown by 0.15.1 which becomes separate jobs on their own. I don't know the reason for adding these additional violations, but the fact that 0.15.1 is not presently not used in production means that this ticket stays valid, isn't it?

**Comment by krzyk** [comment] 2016-01-15 13:44
@prahladyeri no, if it doesn't occur in later releases tickets are not valid, we don't support previous releases at all, only the current one

**Comment by prahladyeri** [comment] 2016-01-15 13:49
@krzyk But there is a problem here moving to the current release. For what you are calling `current` (0.15.1), a `beta` or `cutting-edge` is more appropriate term, whereas the version actually used in netbout project can be termed `current` because it is currently being used.

How do you suggest moving netbout project to qulice 0.15.1 right now?

**Comment by krzyk** [comment] 2016-01-15 13:57
@prahladyeri this way you could say that e.g. guava 1.0 is current, because it is used by a some project, but reality is that guava 19.0 is current, all others are old releases.
Same here, netbout uses probably 0.12, which was released over a year ago, it is not current.

**Comment by prahladyeri** [comment] 2016-01-15 14:21
@krzyk That's true. But there ain't a straightforward way to upgrade us from 0.12 to 0.15.1 without solving a bunch of puzzles first.

Moreover, there is also that case that how much you are that 0.15.1 actually solves this? In that build, is a lot of noise in the form of other classes failing newer validations introduced by 0.15.1. Isn't it possible that after resolution of all those issues, 0.15.1 will still cry for a NPE at line 0?

**Comment by krzyk** [comment] 2016-01-15 14:46
@prahladyeri yes, exactly, so it is best to do a gradual upgrade, first to 0.13, then 0.14, or maybe even 0.13.1, 0.13.2 etc.
You just create a puzzle: "We need to upgrade to the latest qulice (which has this bug fixed) and remove this suppresion". You do only what you can in the budget you get and the rest you "puzzleout", see http://www.yegor256.com/2009/03/04/pdd.html and http://www.yegor256.com/2015/01/15/how-to-cut-corners.html.

**Comment by krzyk** [comment] 2016-01-15 14:47
@prahladyeri if you can prove that NPE is still thrown in 0.15.2, then please show the way to reproduce it using a single class.

**Comment by prahladyeri** [comment] 2016-01-16 09:51
@krzyk Please give me some time to reproduce and prove. I'm currently busy with netbout-web [PR 921](https://github.com/yegor256/netbout/pull/921)

**Comment by krzyk** [comment] 2016-01-16 10:04
@prahladyeri rmember that you can use e.g. `grep` or editors find to check if there is a NPE in `TreeWalker`.
I have to decide if the report is a bug or not in 5 days, so in about 8 hours I'll have to mark it as invalid or not.
Right now I've checked your log outputs and the one for 0.15.1 doesn't have this error, so I assume it doesn't exist.

**Comment by prahladyeri** [comment] 2016-01-17 05:44
@krzyk In that case, go ahead and close this. I'll make a note of this and maybe look more closely and try to reproduce it later when I get time.

**Comment by krzyk** [comment] 2016-01-17 06:06
@prahladyeri you have to close it

**Closed** 2016-01-17 06:11 UTC
