### ISSUE TITLE
How to disable duplicate dependencies check?

### ISSUE THREAD

**Issue by dpisarenko** [teamed/qulice#436] opened 2015-06-02 06:01 UTC
In my `pom.xml` I have following definition:

```
    <build>
        <plugins>
            <plugin>
                <groupId>com.qulice</groupId>
                <artifactId>qulice-maven-plugin</artifactId>
                <version>0.12.1</version>
                <configuration>
                    <license>file:${basedir}/LICENSE.txt</license>
                    <exclude>duplicatefinder:com.github.kodapan</exclude>
                    <exclude>dependencies:com.github.kodapan</exclude>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```
When I run `qulice:check`, the build fails because of these problems:

```
[WARNING] Found duplicate (but equal) classes in [com.github.kodapan:osm-common.core:v0.0.2,se.kodapan.osm.common:core:0.0.2-SNAPSHOT] :
[WARNING]   se.kodapan.lang.Intern
[WARNING]   se.kodapan.osm.domain.OsmObjectVisitor
[WARNING]   se.kodapan.osm.domain.root.AbstractRoot
[WARNING]   se.kodapan.osm.domain.root.Root
```
How can I modify the `exclude` definition above in order for the build to succeed despite these problems (right now, fixing the classpath is out of question) ?

**Comment by davvd** [comment] 2015-06-15 08:20
@yegor256 dispatch this issue please

**Comment by yegor256** [comment] 2015-07-14 00:24
@dpisarenko the only option now is to disable the entire duplicatefinder:

```
<configuration>
  <exclude>duplicatefinder:.*</exclude>
</configuration>
```

**Comment by krzyk** [comment] 2015-11-02 10:28
@dpisarenko is the option mentioned above by @yegor256 enough for you? If so, please close this issue.

**Comment by krzyk** [comment] 2015-11-03 09:56
@dpisarenko also, there is an open issue for extending the duplicate finder #310

**Comment by krzyk** [comment] 2015-11-06 09:58
@davvd duplicate of #310

**Comment by krzyk** [comment] 2015-11-07 12:12
@davvd this is duplicate

**Comment by krzyk** [comment] 2015-11-13 12:20
@davvd this is duplicate

**Comment by krzyk** [comment] 2015-11-13 12:20
@yegor256 looks like @davvd forgot to mark this one as duplicate

**Comment by yegor256** [comment] 2015-11-13 18:43
@krzyk I'll close it

**Closed by yegor256** 2015-11-13 18:43 UTC
