### ISSUE TITLE
Build fails under non-english JVM

### ISSUE THREAD

**Issue by HDouss** [teamed/qulice#519] opened 2015-12-15 18:27 UTC
When we try to build the project under a JVM that don't have english as the default locale, the unit tests fails. This is due to the checkstyle messages that are localized. `com.qulice.checkstyle.CheckstyleValidatorTest` is trying to look for messages like "hides a field" or "Type Javadoc comment is missing" inside Checkstyle output.
The issue is very common under a non-english Windows, where the JVM default locale would be the Windows installation language. The bug is reproducible in a language where localisation is supported in Checkstyle (like French, German, Spanish, Japanese...).
To reprouce the issue in **any** environment, it is enough to run the command : 
`mvn clean install -Pqulice -DargLine="-Duser.language=fr -Duser.country=FR"`

**Comment by krzyk** [comment] 2015-12-16 13:10
@davvd valid bug

**Comment by davvd** [comment] 2015-12-17 09:06
> @davvd valid bug

@krzyk tag bug added to this issue

**Comment by mkordas** [comment] 2015-12-17 20:58
@davvd please assign me to this issue

**Comment by krzyk** [comment] 2015-12-17 21:08
@davvd assign @mkordas please

**Comment by davvd** [comment] 2015-12-18 07:21
> @davvd assign @mkordas please

@krzyk done. @mkordas the task is yours, please go ahead

**Comment by mkordas** [comment] 2015-12-18 07:54
@krzyk please see PR #529

**Comment by davvd** [comment] 2015-12-18 08:50
@hdouss thank you for the ticket reported, I topped your account for 15 mins, transaction `72449864`

**Comment by mkordas** [comment] 2015-12-19 11:24
@HDouss this is done in #529, please close the issue

**Comment by HDouss** [comment] 2015-12-19 19:37
@mkordas  I still have errors due to french localized messages when running : 
`mvn clean install -Pqulice -DargLine="-Duser.language=fr -Duser.country=FR"`
Are you sure the modifications are sufficient ?

**Comment by mkordas** [comment] 2015-12-19 20:46
@HDouss I've double checked and `mvn clean install -Pqulice -DargLine="-Duser.language=fr -Duser.country=FR"` [works for me](https://gist.github.com/mkordas/13c3e0166d9a45ea5f6d) on machine with EN default locale. So the only possibility of failure is `-Duser.language=fr -Duser.country=FR` not being propagated to other JVMs that are spawned during the build. Please submit that as separate issue with clear reproduction steps.

**Comment by HDouss** [comment] 2015-12-19 21:14
@mkordas I am testing on a EN default locale, and where `mvn clean install -Pqulice -DargLine="-Duser.language=fr -Duser.country=FR"` fails. I don't any special reproduction steps other than : 
* Run `mvn clean install -Pqulice` on a non-english default locale JVM
* Run `mvn clean install -Pqulice -DargLine="-Duser.language=fr -Duser.country=FR"` on a english default locale JVM

I tested all possible scenarios on my two environments : 
* English default locale JVM: Running `mvn clean install -Pqulice` -> works fine
* English default locale JVM: Running `mvn clean install -Pqulice -DargLine="-Duser.language=fr -Duser.country=FR"` -> *fails*
* Non English default locale JVM: Always *fails*

**Comment by mkordas** [comment] 2015-12-19 21:46
@HDouss please share all your failing build logs and env details. Here are mine:
```
$ mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/apache-maven
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-39-generic", arch: "amd64", family: "unix"
```
And of course make sure that you are on this commit:
```
$ git log -1
commit 20a15518f62c65e7ee933e4224d562ee7370e990
Author: Michal Kordas <kordas.michal@gmail.com>
Date:   Fri Dec 18 00:45:28 2015 +0100

    #519 Fix build for non-English locale
```

**Comment by HDouss** [comment] 2015-12-20 01:26
@mkordas 
```
mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:4
7+01:00)
Maven home: I:\apache-maven-3.3.9
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: D:\Program Files\Java\jdk1.7.0_45\jre
Default locale: en_US, platform encoding: Cp1256
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
```
Commit history until your last commit : 
```
commit be6b4d77597a41855d1cbcd183b37c6a2e5f2e3f
Author: HDouss <douss.hamdi@gmail.com> 2015-12-19 20:15:24
Committer: HDouss <douss.hamdi@gmail.com> 2015-12-19 20:15:24
Parent: b56bf1541373d316f80f2aa0cc115fb0dbd304bd (Merge pull request #2 from teamed/master)
Parent: 2e985ec677468cfa2b389d7e97d9ea329b8a6585 (Merge branch '__rultor')
Branches: master, origin/master

Merge pull request #3 from teamed/master

update from original repo
```
```
commit 2e985ec677468cfa2b389d7e97d9ea329b8a6585
Author: rultor <me@rultor.com> 2015-12-19 12:01:43
Committer: rultor <me@rultor.com> 2015-12-19 12:01:43
Parent: c38a811bfec5453dda9f842d9b82f70e08c08f68 ( #515 Disallow methods with multiple return statements)
Parent: 20a15518f62c65e7ee933e4224d562ee7370e990 (#519 Fix build for non-English locale)
Child: be6b4d77597a41855d1cbcd183b37c6a2e5f2e3f (Merge pull request #3 from teamed/master)
Branches: master, origin/master

Merge branch '__rultor'
```

```
commit b56bf1541373d316f80f2aa0cc115fb0dbd304bd
Author: HDouss <douss.hamdi@gmail.com> 2015-12-19 10:16:43
Committer: HDouss <douss.hamdi@gmail.com> 2015-12-19 10:16:43
Parent: cd95410073c9813e35ce59e74f3a537f1fea6ab8 (Fix qulice check)
Parent: c38a811bfec5453dda9f842d9b82f70e08c08f68 ( #515 Disallow methods with multiple return statements)
Child: be6b4d77597a41855d1cbcd183b37c6a2e5f2e3f (Merge pull request #3 from teamed/master)
Branches: master, origin/master

Merge pull request #2 from teamed/master

update from original repo
```

```
commit 20a15518f62c65e7ee933e4224d562ee7370e990
Author: Michal Kordas <kordas.michal@gmail.com> 2015-12-18 00:45:28
Committer: Michal Kordas <kordas.michal@gmail.com> 2015-12-19 01:03:13
Parent: afbac010724896e2f2f4c0f471383120bf3e8f97 (Merge branch '__rultor')
Child: 2e985ec677468cfa2b389d7e97d9ea329b8a6585 (Merge branch '__rultor')
Branches: master, origin/master

#519 Fix build for non-English locale

```

**Comment by krzyk** [comment] 2015-12-20 07:04
@HDouss @mkordas this fix is in master version only, so it is visible only in maven invoker tests.  Qulice itself is checked by qulice version 0.12, which doesn't have the fixes. 
Please try to check it with minimal maven project with qulice 1.0.0-SNAPSHOT.

**Comment by HDouss** [comment] 2015-12-20 09:54
@krzyk I don't get your point. The build fails because the unit test is failing and not because a Qulice reported check error.

**Comment by HDouss** [comment] 2015-12-20 13:06
@mkordas same thing if I reposition to commit `20a15518f62c65e7ee933e4224d562ee7370e990`

**Comment by mkordas** [comment] 2015-12-20 20:56
@HDouss you need to be more specific, as the build works for me (evidence at https://gist.github.com/mkordas/13c3e0166d9a45ea5f6d) and I have no possibility to reproduce. Before fixes the build was failing, so my commit definitely improved the situation.
Please raise new issue with the following details:
* full build logs
* information which tests are failing
* information what exactly still needs to be fixed

**Comment by HDouss** [comment] 2015-12-20 21:10
@mkordas I just need to validate. I will try to test on other environments and close the issue as soon as I am able to validate the commit.

**Comment by krzyk** [comment] 2015-12-20 21:15
@HDouss please provide full build logs of the failed case, it will be easier to find the root cause

**Comment by HDouss** [comment] 2015-12-20 21:23
@krzyk I will do it as soon as possible. Could you please confirm that `mvn clean install -Pqulice -DargLine="-Duser.language=fr -Duser.country=FR"` produces a successful build on your environment?

**Comment by krzyk** [comment] 2015-12-20 21:45
@HDouss @mkordas latest master fails for me with:
[build1.txt](https://github.com/teamed/qulice/files/67965/build1.txt)

Command line: `mvn clean install -Pqulice -DargLine="-Duser.language=fr -Duser.country=FR"`

**Comment by HDouss** [comment] 2015-12-20 22:13
@mkordas same for me. Build fails due to french localized messages in unit tests.

**Comment by mkordas** [comment] 2015-12-21 17:20
@HDouss @krzyk actually the build was failing not due to unit tests, but one integration test - please see fix in #537. Most interesting thing here is that test is not run locally for me when I run `mvn clean install -Pqulice` and that's why I wasn't able to reproduce the issue without detailed logs. I'll investigate why not all tests are executed in my env and I'll submit new issue if needed.

**Comment by mkordas** [comment] 2015-12-21 17:21
@davvd please see additional PR #537

**Comment by HDouss** [comment] 2015-12-21 18:12
@mkordas The build fails due to unit test fail.
Please see attached log from @krzyk comment. The failing project is `qulice-checkstyle`. There are no integration tests in that project.

**Comment by mkordas** [comment] 2015-12-21 18:26
@HDouss I'll explain that soon but can you validate the build on 916520d right now?

**Comment by HDouss** [comment] 2015-12-21 18:36
@mkordas [Same results](https://gist.github.com/HDouss/aa53a8195831f51652ca) after integrating your last modifications.

**Comment by mkordas** [comment] 2015-12-21 22:12
@HDouss I have some trace. On my computer everything was fine, but then I changed it to another (faster) one and errors started to appear randomly. So it's all related to parallel execution of tests that is enabled by default and static caching of error messages by Checkstyle - please see https://github.com/checkstyle/checkstyle/blob/bf9325be913ce46a1427232c455f4830b574ba44/src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java#L60.

It's enough to run any unit test for Checkstyle without setting proper locale and then another one in the same JVM (same static cache) even with locale set, but error messages will have mixed languages. 

Please try with commit e8dead0, maybe this will help.

**Comment by HDouss** [comment] 2015-12-21 22:47
@mkordas I am not sure about : 
> It's enough to run any unit test for Checkstyle without setting proper locale and then another one in the same JVM (same static cache) even with locale set, but error messages will have mixed languages.

Because I think the parallel execution is forked on separate java processes (so they don't share the cache).
Anyway the build succeded for me and I will close the issue as soon as PR #537 is merged.
Thanks !

**Comment by mkordas** [comment] 2015-12-21 23:02
> Because I think the parallel execution is forked on separate java processes (so they don't share the cache).

@HDouss indeed, they do not share process with other stuff, but all unit tests share cache between each other and errors in build depend on execution order which is random. We cannot demand from any new test case written to not populate this cache, so that's why I've decided to force English for all unit tests.

**Comment by mkordas** [comment] 2015-12-21 23:02
@davvd please see PR #537

**Comment by davvd** [comment] 2015-12-22 09:09
> @davvd please see PR #537

@mkordas will take a look, thanks

**Comment by mkordas** [comment] 2015-12-22 15:59
@HDouss please close the issue

**Closed** 2015-12-22 16:00 UTC
Labels: 30 mins, bug, DEV

**Comment by mkordas** [comment] 2015-12-22 16:13
@davvd issue is closed (thanks @HDouss), please summarize

**Comment by davvd** [comment] 2015-12-23 08:18
>  @davvd issue is closed (thanks @HDouss), please summarize

@mkordas np :)

**Comment by davvd** [comment] 2015-12-24 08:32
@mkordas thank you, added **30 mins** to your acc, payment num is `567bad12b750bc75f7000025`, 120 hours and 55 mins spent in total to complete; +30 added to your rating, at the moment it is: [+764](http://www.netbout.com/b/36080?open=rating)
