### ISSUE TITLE
IndentationCheck is incorrect with builder style method calls in parameters.

### ISSUE THREAD

**Issue by piddubnyi** [teamed/qulice#687] opened 2016-02-04 12:42 UTC
It's common in teamed projects to use builder style method calls in parameters, however qulice forces incorrect format them. For example following code will cause IndentationCheck error, but for my opinion it is correctly formatted.
```java
new Foo()
    .bar(
        new Foo()
            .bar(
                new Foo()
            )
            .bar(
                new Foo()
            )
    );
```

**Comment by krzyk** [comment] 2016-02-04 20:20
@piddubnyi isn't it a duplicate of #449

**Comment by piddubnyi** [comment] 2016-02-04 20:30
@krzyk yes right.

**Closed** 2016-02-04 20:31 UTC
