### ISSUE TITLE
NPE with qulice

### ISSUE THREAD

**Issue by marty-buly** [teamed/qulice#448] opened 2015-07-27 15:04 UTC
I took maven configuration directly from www.qulice.com and placed it in our parent pom.xml file to enable this for all children projects.

Now parent project (which is pom type) builds successfully, but first child project fails with NPE.

I'm using Maven 3.2.5, as I thought it is related to #417 and #439 (but this seems to be another issue).

```
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.12.1:check (default-cli) on project sr-as1-common-global-util: Execution default-cli of goal com.qulice:qulice-maven-plugin:0.12.1:check failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qulice:qulice-maven-plugin:0.12.1:check (default-cli) on project sr-as1-common-global-util: Execution default-cli of goal com.qulice:qulice-maven-plugin:0.12.1:check failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.qulice:qulice-maven-plugin:0.12.1:check failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.NullPointerException
	at com.qulice.maven.DefaultMavenEnvironment.classpath(DefaultMavenEnvironment.java:140)
	at com.qulice.maven.DefaultMavenEnvironment.classloader(DefaultMavenEnvironment.java:156)
	at com.qulice.checkstyle.CheckstyleValidator.validate(CheckstyleValidator.java:81)
	at com.qulice.maven.CheckMojo.run(CheckMojo.java:83)
	at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:59)
	at com.qulice.maven.AbstractQuliceMojo.execute(AbstractQuliceMojo.java:175)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more
```

**Comment by davvd** [comment] 2015-07-31 07:33
@yegor256 please dispatch this issue

**Comment by yegor256** [comment] 2015-08-01 01:29
@marty-buly indeed, it's something else... thanks for reporting, we'll try to fix ASAP

**Comment by davvd** [comment] 2015-08-03 08:37
@krzyk it's yours, budget is 30 mins, please go ahead

**Comment by krzyk** [comment] 2015-08-03 11:57
@marty-buly do you have a small test project that fails with qulice (basically a Short, Self Contained, Correct Example)? I tried to reproduce it but it always works for me in multi module project, and I have no idea what might cause NPE here.

**Comment by krzyk** [comment] 2015-08-07 06:09
@davvd please give me more time

**Comment by krzyk** [comment] 2015-08-07 06:10
@marty-buly if you don't have have enough time for creating an example, maybe you could share some specifics about your project module structure? Do you use other plugins, do you use code generation tools and anything that is non standard?

**Comment by marty-buly** [comment] 2015-08-07 06:47
@krzyk apologise, yeap I had no time for now and forgot to place here message. I'll have more time today and will update you on the configuration of our project. thnx

**Comment by marty-buly** [comment] 2015-08-07 09:06
@krzyk I found what the issue is:
We are having following dependency
		<dependency>
			<groupId>activation</groupId>
			<artifactId>activation</artifactId>
			<version>1.0.2</version>
		</dependency>
When I had a look then there is no jar file behind, but there is just pom.xml present in the maven repository with following content:
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>activation</groupId>
  <artifactId>activation</artifactId>
  <version>1.0.2</version>

  <distributionManagement>
    <relocation>
      <groupId>javax.activation</groupId>
    </relocation>
  </distributionManagement>

</project> 

So the issue seems to be that qulice cannot resolve this dependency thru relocation.

When I replace our dependency with the javax.activation one then it works.

**Comment by krzyk** [comment] 2015-08-08 12:46
@marty-buly here's the PR #452  that should fix the problem (I used similar dependency in integration test as javax.activation:activation is not available in maven central)

**Comment by davvd** [comment] 2015-08-11 08:06
> @davvd please give me more time

@krzyk OK, no problem, take your time

**Comment by krzyk** [comment] 2015-08-11 09:31
@marty-buly could you try the latest snapshot of qulice? It shouldn't have this problem

**Comment by yegor256** [comment] 2015-08-11 13:00
@marty-buly 0.12.2 should work

**Comment by marty-buly** [comment] 2015-08-11 13:09
@yegor256 have you changed the minimum java version with 0.12.2?

I'm receiving this:
An API incompatibility was encountered while executing com.qulice:qulice-maven-plugin:0.12.2:check: java.lang.UnsupportedClassVersionError: com/puppycrawl/tools/checkstyle/api/CheckstyleException : Unsupported major.minor version 51.0

**Comment by marty-buly** [comment] 2015-08-11 13:20
@yegor256 @krzyk after the change from java 1.6 to 1.7, I'm able to run the qulice successfully
I can confirm, that error is fixed...

nevertheless I don't think, that change of the java version between 0.12.1 & 0.12.2 is good practice - but I agree, you are still in experimental mode ;)

thnx for efforts

**Comment by krzyk** [comment] 2015-08-11 13:58
@marty-buly strange, you got probably lucky because we migrated to 1.7 year ago (PMD and Findbugs at least) :), but we were still using old checkstyle, which was upgraded between 0.12.1 and 0.12.2, new checkstyle is only for 1.7.

**Comment by krzyk** [comment] 2015-08-11 13:59
@marty-buly please close this issue, thanks

**Closed** 2015-08-11 14:02 UTC
Labels: 30 mins, @krzyk, DEV

**Comment by davvd** [comment] 2015-08-13 07:35
@krzyk Thanks for your contribution, **30 mins** was added to your account, payment ID is `63013652`, 214 hours and 49 mins spent total. added +30 to your rating, now it is equal to [+4250](http://www.netbout.com/b/35035?open=rating)
