### ISSUE TITLE
Build fails on Windows if javac is not in PATH

### ISSUE THREAD

**Issue by palyuga** [teamed/qulice#380] opened 2015-01-14 14:03 UTC
I have multiple test fails on Windows if there is no `javac` in `PATH`, like this one:

`throwsExceptionOnViolation(com.qulice.findbugs.FindBugsValidatorTest)  Time elapsed: 0.068 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<com.qulice.spi.ValidationException> but was<java.io.IOException>
...
Caused by: java.io.IOException: Cannot run program "javac": CreateProcess error=2`

Don't think we can do something with it, but at least INSTALL.txt should contain info about `path/to/sdk/bin` must be in `PATH`

**Comment by yegor256** [comment] 2015-01-14 23:07
@palyuga that's true, we should explain this in README, thanks for reporting

**Comment by davvd** [comment] 2015-01-16 11:58
I'll ask someone to take care of this task soon

**Comment by davvd** [comment] 2015-01-19 09:24
@pinaf this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here... **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by pinaf** [comment] 2015-01-19 17:07
@davvd please see PR #387

**Comment by pinaf** [comment] 2015-01-20 17:55
@davvd @palyuga merged, please close.

**Closed** 2015-01-20 19:54 UTC
Labels: 30 mins, bug, DEV

**Comment by pinaf** [comment] 2015-01-22 00:19
@davvd issue fixed and closed!

**Comment by davvd** [comment] 2015-01-22 07:53
@pinaf Much appreciated! **30 mins** was added to your account, payment ID `AP-7VG4767155389564N`

+30 added to your rating, at the moment it is: [+135](http://www.netbout.com/b/35128?open=rating)
