### ISSUE TITLE
Qulice fails with NullPointerException.

### ISSUE THREAD

**Issue by kujtimiihoxha** [teamed/qulice#676] opened 2016-02-03 08:54 UTC
I am trying to exclude a folder from checkstyle,pmd,findbugs but if I add 
```
 <exclude>findbugs:~com.interadria.bms.entity.*</exclude>
```
build fails with this message 
```[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.15.5:check (default) on project iaserver-entity: Execution default of goal com.qulice:qulice-maven-plugin:0.15.5:check
 failed. NullPointerException -> [Help 1]```


pom.xml

```
   <build>
        <plugins>
            <plugin>
                <groupId>com.qulice</groupId>
                <artifactId>qulice-maven-plugin</artifactId>
                <version>0.15.5</version>
                <configuration>
                    <license>file:${basedir}/LICENCE.txt</license>
                    <excludes>
                        <exclude>checkstyle:/src/main/java/com/interadria/bms/entity/model/.*</exclude>
                        <exclude>pmd:/src/main/java/com/interadria/bms/entity/model/.*</exclude>
                        <exclude>findbugs:~com.interadria.bms.entity.*</exclude>
                        <exclude>xml:/src/main/java/com/interadria/bms/entity/hibernate.cfg.xml</exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

**Comment by krzyk** [comment] 2016-02-03 10:03
@kujtimiihoxha I can't reproduce it, could you provide logs with `mvn -X`?

**Comment by mkordas** [comment] 2016-02-03 10:21
@kujtimiihoxha do you use Maven > 3.1.0?

**Comment by kujtimiihoxha** [comment] 2016-02-03 10:41
@mkordas  I am using ```maven-3.3.9```

@krzyk  here is the output of  ```mvn clean install -Pqulice -X ```  
[out.txt](https://github.com/teamed/qulice/files/115471/out.txt)

**Comment by krzyk** [comment] 2016-02-03 11:07
@kujtimiihoxha OK, so the problem is in `DependenciesValidator`:
```
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.15.5:check (default) on project iaserver-entity: Execution default of goal com.qulice:qulice-maven-plugin:0.15.5:check failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qulice:qulice-maven-plugin:0.15.5:check (default) on project iaserver-entity: Execution default of goal com.qulice:qulice-maven-plugin:0.15.5:check failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.qulice:qulice-maven-plugin:0.15.5:check failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at java.lang.String.startsWith(String.java:1405)
	at java.lang.String.startsWith(String.java:1434)
	at com.qulice.maven.DependenciesValidator$ExcludePredicate.apply(DependenciesValidator.java:186)
	at com.qulice.maven.DependenciesValidator$ExcludePredicate.apply(DependenciesValidator.java:167)
	at com.google.common.base.Predicates$NotPredicate.apply(Predicates.java:335)
	at com.google.common.collect.Iterators.indexOf(Iterators.java:796)
	at com.google.common.collect.Iterators.any(Iterators.java:706)
	at com.google.common.collect.Iterables.any(Iterables.java:621)
	at com.google.common.collect.Collections2$FilteredCollection.isEmpty(Collections2.java:184)
	at com.qulice.maven.DependenciesValidator.validate(DependenciesValidator.java:78)
	at com.qulice.maven.CheckMojo.run(CheckMojo.java:88)
	at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:59)
	at com.qulice.maven.AbstractQuliceMojo.execute(AbstractQuliceMojo.java:176)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

**Comment by krzyk** [comment] 2016-02-03 11:09
@davvd valid bug

**Comment by krzyk** [comment] 2016-02-03 11:09
@kujtimiihoxha thanks

**Comment by davvd** [comment] 2016-02-04 07:12
> @davvd valid bug

@krzyk tagged this issue with "bug"

**Comment by krzyk** [comment] 2016-02-05 08:34
@kujtimiihoxha could you share dependency list? Or maybe you know which dependency cause this problem? It might be some tricky one, e.g. with packaging `pom` or, scope `runtime` or anything not common.

**Comment by kujtimiihoxha** [comment] 2016-02-05 08:38
@krzyk  Here are my dependencies 
```
  <!-- for JPA, use hibernate-entitymanager instead of hibernate-core -->
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-entitymanager</artifactId>
            <version>5.0.7.Final</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.38</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
```

**Comment by longtimeago** [comment] 2016-02-06 21:29
@krzyk experienced the same issue http://www.rultor.com/t/6562-180864098

**Comment by longtimeago** [comment] 2016-02-06 21:49
@krzyk `env.excludes("dependencies")` https://github.com/teamed/qulice/blob/6ef5d1056b0ea93144f7d99cfbd4fc829a0c5e9b/qulice-maven-plugin/src/main/java/com/qulice/maven/DependenciesValidator.java#L66
returns a collection with nulls.
For example, we have qulice config
```xml
                            <excludes combine.children="append">
                                <exclude>checkstyle:/src/it/.*/*.txt</exclude>
                                <exclude>findbugs:.*</exclude>
                                <exclude>xml:/src/it/.*</exclude>
                            </excludes>
```
In this case `excludes` content is ```[null, null, null]```

**Comment by krzyk** [comment] 2016-02-07 15:54
@longtimeago oops, I'll try to find a volunteer as soon as davvd will allow another issue assigned.

**Comment by longtimeago** [comment] 2016-02-07 15:56
@krzyk thanks, hope to see it resolved soon :)

**Comment by krzyk** [comment] 2016-02-07 16:19
@davvd this is urgent

**Comment by davvd** [comment] 2016-02-08 09:44
> @davvd this is urgent

@krzyk got it, "urgent" label here

**Comment by davvd** [comment] 2016-02-08 11:37
@vkuchyn it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket. The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by vkuchyn** [comment] 2016-02-08 12:41
@davvd Links you provided are not valid - 404 status code. Use [out principles](http://www.yegor256.com/2014/04/17/how-xdsd-is-different.html) and [DoD](http://www.yegor256.com//2014/04/15/definition-of-done.html) instead

**Comment by vkuchyn** [comment] 2016-02-09 20:53
@kujtimiihoxha Fixed at #696

**Comment by kujtimiihoxha** [comment] 2016-02-09 21:02
@vkuchyn Thanks

**Comment by vkuchyn** [comment] 2016-02-09 21:14
@kujtimiihoxha Please, close the ticket if you don't mind. These changes will be in next release (0.17 I guess) or you can try to build plugin from the sources and try it on your project

**Comment by krzyk** [comment] 2016-02-09 21:34
@vkuchyn @kujtimiihoxha it will be in 0.16.1, which will be released in about an hour

**Closed** 2016-02-09 21:33 UTC
Labels: 30 mins, bug, DEV, urgent

**Comment by longtimeago** [comment] 2016-02-10 06:25
@krzyk thank you for the fast turnaround! :)

**Comment by davvd** [comment] 2016-02-10 08:22
> @davvd Links you provided are not valid - 404 status code. Use [out principles](http://www.yegor256.com/2014/04/17/how-xdsd-is-different.html) and [DoD](http://www.yegor256.com//2014/04/15/definition-of-done.html) instead

@vkuchyn they both work for me... try to check again

**Comment by davvd** [comment] 2016-02-10 08:23
@kujtimiihoxha there is a puzzle in this code `676-be080182`/#699, we'll resolve it later

**Comment by davvd** [comment] 2016-02-11 11:07
@vkuchyn done, I added **45 mins** in payment `77163415`, 44 hours and 45 mins spent to complete this; the bonus for fast delivery (m=2685); +45 added to your rating, at the moment it is: [+90](http://www.netbout.com/b/36353?open=rating)

**Comment by krzyk** [comment] 2016-03-02 09:02
@davvd this is not urgent

**Comment by davvd** [comment] 2016-03-02 10:22
> @davvd this is not urgent

@krzyk sure, thanks, I removed "urgent" tag to it

**Comment by davvd** [comment] 2016-04-18 10:09
@kujtimiihoxha the last puzzle `676-be080182`/#699 originated from here solved
